#!/bin/bash

echo "=== Terminal Blog Deployment ==="
echo ""
echo "On your server, run:"
echo ""
echo "  sudo bash -c '"
echo "    # Clone the deploy script"
echo "    wget https://raw.githubusercontent.com/yah0130/terminal-blog/main/deploy.sh -O /tmp/deploy.sh"
echo "    chmod +x /tmp/deploy.sh"
echo "    cd /tmp"
echo "    bash /tmp/deploy.sh"
echo "  '"
echo ""
echo "Or if you already have deploy.sh on your server, just run:"
echo "  sudo bash /tmp/deploy.sh"
